os: linux
dist: xenial

if: tag IS blank
branches:
  only:
    # Master
    - master
    # Release branches
    - /^release\/.+$/
    # Develop
    - develop

language: python
python:
  - "2.7"

services:
  - docker

before_script:
  - sudo service mysql stop
  - ./develop build
  - ./develop up -d
  - ./develop npm ci
  - ./develop npm run dev
  - ./develop composer install
  - ./develop run --rm -T app mv .env.example .env
  - ./develop artisan key:generate
  - ./develop artisan passport:keys

script:
  - ./develop composer test:style
  - ./develop composer test:unit

after_failure:
  - cat storage/logs/testing.log

before_deploy: |
  if ! [[ ${HAS_RAN_BEFORE_DEPLOY} ]]; then
    export HAS_RAN_BEFORE_DEPLOY="TRUE"

    echo "Compiling assets for production..."
    ./develop npm run prod

    echo "Installing AWS CLI..."
    curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
    unzip awscli-bundle.zip
    sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
  fi

deploy:
  # Tagged releases
  - provider: script
    script: >
      bash /.travis/deploy.sh production ${REPO_URI_PRODUCTION} ${CLUSTER_PRODUCTION}
      ${AWS_ACCESS_KEY_ID_PRODUCTION} ${AWS_SECRET_ACCESS_KEY_PRODUCTION} ${AWS_DEFAULT_REGION_PRODUCTION}
    skip_cleanup: true
    on:
      all_branches: true
      condition: ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^[0-9]{4}\.[0-9]{2}\.[0-9]{2}\.[0-9]+$
  # Release branches
  - provider: script
    script: >
      bash /.travis/deploy.sh release ${REPO_URI_RELEASE} ${CLUSTER_RELEASE}
      ${AWS_ACCESS_KEY_ID_RELEASE} ${AWS_SECRET_ACCESS_KEY_RELEASE} ${AWS_DEFAULT_REGION_RELEASE}
    skip_cleanup: true
    on:
      all_branches: true
      condition: ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^release\/.+$
  # Develop
  - provider: script
    script: >
      bash /.travis/deploy.sh staging ${REPO_URI_STAGING} ${CLUSTER_STAGING}
      ${AWS_ACCESS_KEY_ID_STAGING} ${AWS_SECRET_ACCESS_KEY_STAGING} ${AWS_DEFAULT_REGION_STAGING}
    skip_cleanup: true
    on:
      branch: develop
